MVCBasics/MVCBasics/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCBasics.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCBasics.Controllers
{
    [Authorize(Roles = "Admin, Registrar")]
    public class CourseController : Controller
    {
        public CourseController(
            ICrudService<Student> studentService,
            ICrudService<Course> courseService,
            SchoolDbContext ctx
        ) {
            this.studentService = studentService;
            this.courseService = courseService;
            this.ctx = ctx;
        }
        
        private ICrudService<Student> studentService;
        private ICrudService<Course> courseService;
        private SchoolDbContext ctx;

        #region Create
        public IActionResult Create()
        {
            return View("Edit", new Course());
        }
        [HttpPost]
        public async Task<IActionResult> Create(Course course)
        {
            if (ModelState.IsValid)
            {
                course = await courseService.CreateAsync(course);
                if (course == null) return RedirectToAction("List");
                return RedirectToAction("View", new { course.Id });
            }
            else
            {
                return View("Edit", course);
            }
        }
        #endregion

        #region Read
        public IActionResult List()
        {
            var courses = ctx.Courses.Include(course => course.Teacher).AsEnumerable().ToArray();
            var school = new SchoolViewModel()
            {
                Name = "Neumont College of Computer Science",
                Courses = courses
            };
            return View(school);
        }

        public IActionResult View(int id)
        {
            var course = ctx.Courses
                .Include(c => c.Teacher)
                .Include(c => c.Enrollments)
                .ThenInclude(e => e.Student)
                .Where(c => c.Id == id)
                .FirstOrDefault();
            if (course == null) return RedirectToAction("List");
            return View(course);
        }
        #endregion

        #region Update
        public async Task<IActionResult> Edit(int id)
        {
            var course = await this.courseService.GetAsync(id);
            return View(course);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Course course)
        {
            if (ModelState.IsValid)
            {
                await courseService.UpdateAsync(course);
                return RedirectToAction("View", new { course.Id });
            }
            else
            {
                return View(course);
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddStudent(int id)
        {
            if (int.TryParse(Request.Form["StudentId"], out var studentId) && Enum.TryParse<LetterGrade>(Request.Form["LetterGrade"], out var letterGrade))
            {
                var student = await studentService.GetAsync(studentId);
                var course = await courseService.GetAsync(id);
                if (course != null && student != null)
                {
                    var preexisting = ctx.Enrollments
                        .Where(e => e.CourseId == id && e.StudentId == studentId)
                        .FirstOrDefault();
                    if (preexisting == null)
                    {
                        await ctx.Enrollments.AddAsync(new Enrollment()
                        {
                            StudentId = studentId,
                            CourseId = id,
                            Grade = letterGrade
                        });
                    }
                    else if (preexisting.Grade != letterGrade)
                    {
                        preexisting.Grade = letterGrade;
                        ctx.Enrollments.Update(preexisting);
                    }
                    await ctx.SaveChangesAsync();
                }
            }
            return RedirectToAction("View", new { Id = id });
        }
        
        public async Task<IActionResult> RemoveStudent(int id, int secondaryId)
        {
            var courseId = id;
            var studentId = secondaryId;
            var course = await courseService.GetAsync(id);
            var student = await studentService.GetAsync(studentId);
            if (course != null && student != null)
            {
                var preexisting = ctx.Enrollments
                    .Where(e => e.CourseId == id && e.StudentId == studentId)
                    .FirstOrDefault();
                if (preexisting != null)
                {
                    ctx.Remove(preexisting);
                    await ctx.SaveChangesAsync();
                }
            }
            return RedirectToAction("View", new { Id = id });
        }
        #endregion

        #region Destroy
        public async Task<IActionResult> Destroy(int id)
        {
            await this.courseService.DestroyAsync(id);
            return RedirectToAction("List");
        }
        #endregion
    }
}

MVCBasics/MVCBasics/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCBasics.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCBasics.Controllers
{
    public class StudentController : Controller
    {
        public StudentController(
            ICrudService<Student> studentService,
            ICrudService<Course> courseService,
            SchoolDbContext ctx
        ) {
            this.studentService = studentService;
            this.ctx = ctx;
        }
        
        private ICrudService<Student> studentService;
        private SchoolDbContext ctx;

        #region Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View("Edit", new Student());
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Student student)
        {
            if (ModelState.IsValid)
            {
                student = await studentService.CreateAsync(student);
                if (student == null) return RedirectToAction("List");
                return RedirectToAction("View", new { student.Id });
            }
            else
            {
                return View("Edit", student);
            }
        }
        #endregion

        #region Read
        [Authorize(Roles = "Admin, Registrar")]
        public async Task<IActionResult> List()
        {
            var school = new SchoolViewModel()
            {
                Name = "Neumont College of Computer Science",
                Students = (await studentService.FindAllAsync()).ToArray()
            };
            return View(school);
        }

        [Authorize(Policy = "StudentIsSelf")]
        public IActionResult View(int id)
        {
            var student = ctx.Students
                .Include(c => c.Enrollments)
                .ThenInclude(e => e.Course)
                .Where(c => c.Id == id)
                .FirstOrDefault();
            if (student == null) return RedirectToAction("List");
            return View(student);
        }
        #endregion

        #region Update
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var student = await this.studentService.GetAsync(id);
            if (student == null) return RedirectToAction("List");
            return View(student);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, Student student)
        {
            if (ModelState.IsValid)
            {
                await studentService.UpdateAsync(student);
                return RedirectToAction("View", new { Id = id });
            }
            else
            {
                return View(student);
            }
        }
        #endregion

        #region Destroy
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Destroy(int id)
        {
            await this.studentService.DestroyAsync(id);
            return RedirectToAction("List");
        }
        #endregion
    }
}

MVCBasics/MVCBasics/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCBasics.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCBasics.Controllers
{
    public class TeacherController : Controller
    {
        public TeacherController(
            ICrudService<Teacher> teacherService,
            ICrudService<Student> studentService
        ) {
            this.teacherService = teacherService;
        }

        private ICrudService<Teacher> teacherService;

        #region Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View("Edit", new Teacher());
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                teacher = await teacherService.CreateAsync(teacher);
                if (teacher == null) return RedirectToAction("List");
                return RedirectToAction("View", new { teacher.Id });
            }
            else
            {
                return View("Edit", teacher);
            }
        }
        #endregion

        #region Read
        [Authorize(Roles = "Admin, Registrar")]
        public async Task<IActionResult> List()
        {
            var school = new SchoolViewModel()
            {
                Name = "Neumont College of Computer Science",
                Teachers = (await teacherService.FindAllAsync()).ToArray()
            };
            return View(school);
        }

        [Authorize(Policy = "TeacherIsSelf")]
        public async Task<IActionResult> View(int id)
        {
            var teacher = await this.teacherService.GetAsync(id);
            if (teacher == null) return RedirectToAction("List");
            return View(teacher);
        }
        #endregion

        #region Update
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var teacher = await this.teacherService.GetAsync(id);
            return View(teacher);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                await teacherService.UpdateAsync(teacher);
                return RedirectToAction("View", new { teacher.Id });
            }
            else
            {
                return View(teacher);
            }
        }
        #endregion

        #region Destroy
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Destroy(int id)
        {
            await this.teacherService.DestroyAsync(id);
            return RedirectToAction("List");
        }
        #endregion
    }
}

MVCBasics/MVCBasics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCBasics</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="~/lib/fontawesome/js/fontawesome-all.js" asp-append-version="true" defer></script>
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <script src="~/lib/fontawesome/js/fontawesome-all.min.js" asp-append-version="true" defer></script>
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <div class="container body-content">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                    </li>
                    @if ((ViewContext.HttpContext.User?.IsInRole("Admin") ?? false) || (ViewContext.HttpContext.User?.IsInRole("Registrar") ?? false))
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List", "Student")">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List", "Teacher")">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List", "Course")">Courses</a>
                        </li>
                    }
                    @if (ViewContext.HttpContext.User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Statistics", "Statistics")">Statistics</a>
                        </li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </nav>

        @RenderBody()

        <footer>
            <hr />
            <p>&copy; 2018 - MVCBasics</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>